service: serverless-graphql

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: gatsby-core
  credentials: ~/Downloads/gatsby-core.json

functions:
  public:
    handler: public
    events:
      - http: foo
  graphql:
    handler: graphql
    events:
      - http: foo
